let charmsInfo = [['Joni Blessing',-507, 1465,'icon/charms/joni_blessing.png','',1,'charms'],
                     ['Baldur Shell',-665, 1303,'icon/charms/baldur_shell.png','',1,'charms'],
                     ['Fury of The Fallen',-655, 1720,'icon/charms/fury_of_the_fallen.png','',1,'charms'],
                     ['Grimm Child',-620,1888,'icon/charms/grimm_child.png','',1,'charms'],
                     ['Nailmaster Glory',-599, 1978,'icon/charms/nailmaster_glory.png','',1,'charms'],
                     ['Deep Focus',-644, 2481,'icon/charms/deep_focus.png','',1,'charms'],
                     ['Shape of Unn',-909, 373,'icon/charms/shape_of_unn.png','',1,'charms'],
                     ['Thorns of Agony',-931, 1287,'icon/charms/thorns_of_agony.png','',1,'charms'],
                     ['Soul Catcher',-817, 2055,'icon/charms/soul_catcher.png','',1,'charms'],
                     ['Glowing Womb',-801, 2335,'icon/charms/glowing_womb.png','',1,'charms'],
                     ['Dream Shield',-856, 3318,'icon/charms/dream_shield.png','',1,'charms'],
                     ['Soul Eater',-982, 3738,'icon/charms/soul_eater.png','',1,'charms'],
                     ['King Soul Left',-1147, 546,'icon/charms/king_soul_part1.png','',0.5,'charms'],
                     ['Spore Shroom',-1547, 1506,'icon/charms/spore_shroom.png','',1,'charms'],
                     ['Mark of Pride',-1713, 1948,'icon/charms/mark_of_pride.png','',1,'charms'],
                     ['Dash Master',-1832, 1991,'icon/charms/dash_master.png','',1,'charms'],
                     ['Spell Twister',-1213, 2818,'icon/charms/spell_twister.png','',1,'charms'],
                     ['Weaversong',-1940, 998,'icon/charms/weaversong.png','',1,'charms'],
                     ['Sharp Shadow',-2175, 1692,'icon/charms/sharp_shadow.png','',1,'charms'],
                     ['Flukenest',-1956, 2416,'icon/charms/flukenest.png','',1,'charms'],
                     ['Defender Crest',-1809, 2960,'icon/charms/defender_crest.png','',1,'charms'],
                     ['Quick Slash',-1913, 4151,'icon/charms/quick_slash.png','',1,'charms'],
                     ['Hiverblood',-1986,4071,'icon/charms/hiverblood.png','',1,'charms'],
                     ['King Soul Right',-2226, 3042,'icon/charms/king_soul_part2.png','',0.5,'charms'],
                     ['Lifeblood Core',-2638, 2551,'icon/charms/lifeblood_core.png','',1,'charms'],
                     ['Void Heart',-2812, 2721,'icon/charms/void_heart.png','Unlock 2 Endings',0,'charms'],
                     ['Unbreakable Greed',-605,1840,'icon/charms/unbreakable_greed.png','',0,'charms'],
                     ['Unbreakable Heart',-605,1855,'icon/charms/unbreakable_heart.png','',0,'charms'],
                     ['Unbreakable Strength',-605,1870,'icon/charms/unbreakable_strength.png','',0,'charms'],
                     ['Grubsong',-696,1874,'icon/charms/grubsong.png','',1,'charms'],
                     ['Grubberfly\'s Elegy',-696,1886,'icon/charms/grubberfly_elegy.png','',1,'charms'],
                     ['Gathering Swarm',-587,1955,'icon/charms/gathering_swarm.png','',1,'charms'],
                     ['Stalwart Shell',-587,1967,'icon/charms/stalwart_shell.png','',1,'charms'],
                     ['Heavy Blow',-587,1979,'icon/charms/heavy_blow.png','',1,'charms'],
                     ['Sprintmaster Shell',-587,1991,'icon/charms/sprintmaster.png','',1,'charms'],
                     ['Wayward Compass',-599, 2041,'icon/charms/wayward_compass.png','',1,'charms'],
                     ['Fragile Greed',-1182,2100,'icon/charms/fragile_greed.png','',1,'charms'],
                     ['Fragile Heart',-1182,2112,'icon/charms/fragile_heart.png','',1,'charms'],
                     ['Fragile Strength',-1182,2124,'icon/charms/fragile_strength.png','',1,'charms'],
                     ['Lifeblood Heart',-1006,2662,'icon/charms/lifeblood_heart.png','',1,'charms'],
                     ['Longnail',-1006,2674,'icon/charms/long_nail.png','',1,'charms'],
                     ['Steady Body',-1006,2686,'icon/charms/steady_body.png','',1,'charms'],
                     ['Shaman Stone',-993,2662,'icon/charms/shaman_stone.png','',1,'charms'],
                     ['Quick Focus',-993,2674,'icon/charms/quick_focus.png','',1,'charms'],
                     ['Dream Wielder',-804,3421,'icon/charms/dream_wielder.png','',1,'charms'],]