let maskshardInfo = [['Mask Shard',-575,1955,'icon/mask_shard.png','<br>Just Sly',0.25,'maskshard'],
                         ['Mask Shard',-575,1967,'icon/mask_shard.png','<br>Just Sly',0.25,'maskshard'],
                         ['Mask Shard',-575,1979,'icon/mask_shard.png','<br>Sly With Shopkeeper Key',0.25,'maskshard'],
                         ['Mask Shard',-575,1991,'icon/mask_shard.png','<br>Sly With Shopkeeper Key',0.25,'maskshard'],
                         ['Mask Shard',-872,1935,'icon/mask_shard.png','<br>Reward for defeating Brooding Mawlek',0.25,'maskshard'],
                         ['Mask Shard',-696,1898,'icon/mask_shard.png','<br>Requires rescuing 5 Grubs',0.25,'maskshard'],
                         ['Mask Shard',-940,2122,'icon/mask_shard.png','<br>Recomended Mantis Claw',0.25,'maskshard'],
                         ['Mask Shard',-1414,1606,'icon/mask_shard.png','<br>Requires Mantis Claw',0.25,'maskshard'],
                         ['Mask Shard',-828,2063,'icon/mask_shard.png','<br>Requires rescuing Bretta from Fungal Wastes',0.25,'maskshard'],
                         ['Mask Shard',-908,2027,'icon/mask_shard.png','<br>Recommended Lumafly Lantern',0.25,'maskshard'],
                         ['Mask Shard',-1814,2157,'icon/mask_shard.png','',0.25,'maskshard'],
                         ['Mask Shard',-1839,1700,'icon/mask_shard.png','<br>Requires Monarch Wings',0.25,'maskshard'],
                         ['Mask Shard',-485,2835,'icon/mask_shard.png','<br>Requires Monarch Wings',0.25,'maskshard'],
                         ['Mask Shard',-1968,3812,'icon/mask_shard.png','<br>Requires baiting a Hive Guardian into breaking a wall',0.25,'maskshard'],
                         ['Mask Shard',-804,3431,'icon/mask_shard.png','<br>Requires collecting 1500 Essence',0.25,'maskshard'],
                         ['Mask Shard',-936,3662,'icon/mask_shard.png','<br>Requires completing the Delicate Flower quest',0.25,'maskshard'],]